version: '3.8'

services:
  ollama:
    build:
      context: ./ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama

  backend:
    build:
      context: ./backend
    ports:
      - "5001:5001"

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  ollama:

networks:
  default:
    name: myapp-network